const express = require('express')
const app = express()
const studentsRouter = require('./controllers/students')
const teachersRouter = require('./controllers/teachers')
const coursesRouter = require('./controllers/courses')
const departmentsRouter = require('./controllers/departments')
const majorsRouter = require('./controllers/majors')
const classesRouter = require('./controllers/classes')
const courseselectionsRouter = require('./controllers/courseselections')
const usersRouter = require('./controllers/users')
const loginsRouter = require('./controllers/logins')
const studentinfosRouter = require('./controllers/studentinfos')
const studentselectedcoursesRouter = require('./controllers/studentselectedcourses')
const studentcoursecatalogsRouter = require('./controllers/studentcoursecatalogs')
const changepasswordsRouter = require('./controllers/changepasswords')
const teacherinfosRouter = require('./controllers/teacherinfos')
const teachercoursesRouter = require('./controllers/teachercourses')


app.use(express.json())
app.use('/api/students', studentsRouter)
app.use('/api/teachers', teachersRouter)
app.use('/api/courses', coursesRouter)
app.use('/api/departments', departmentsRouter)
app.use('/api/majors', majorsRouter)
app.use('/api/classes', classesRouter)
app.use('/api/courseselections', courseselectionsRouter)
app.use('/api/users', usersRouter)
app.use('/api/logins', loginsRouter)
app.use('/api/studentinfos', studentinfosRouter)
app.use('/api/studentselectedcourses', studentselectedcoursesRouter)
app.use('/api/studentcoursecatalogs', studentcoursecatalogsRouter)
app.use('/api/changepasswords', changepasswordsRouter)
app.use('/api/teacherinfos', teacherinfosRouter)
app.use('/api/teachercourses', teachercoursesRouter)


module.exports = app
